// Pure codegen: (options, resolved ids) -> { workerSource, wranglerConfig }.
// No I/O. The golden tests pin this module's output — in particular the
// Durable Object migrations ledger, which is append-only on live workers.
export function generate(options, { d1Id = null, kvId = null, accountId = null, schemaPath = null } = {}) {
	const {
		name, d1Name, emailFrom, queueName, crons = [], useBroadcast,
		r2Bucket, kvNamespace, customDomain, wasmVariant, extraEnv = {},
	} = options;

	const envVarsLiteral = JSON.stringify({
		APP_NAME: name,
		...(d1Name ? { DB_CONNECTION: 'cfd1', D1_BINDING: 'DB' } : {}),
		...(emailFrom ? { MAIL_MAILER: 'cloudflare', MAIL_FROM_ADDRESS: emailFrom } : {}),
		...(queueName ? { QUEUE_CONNECTION: 'cloudflare' } : {}),
		...(useBroadcast ? { BROADCAST_CONNECTION: 'cloudflare' } : {}),
		...(r2Bucket ? { FILESYSTEM_DISK: 'r2' } : {}),
		...(kvNamespace ? { CACHE_STORE: 'kv' } : {}),
		...extraEnv,
	});

	// The baked config cache froze bake-time values, so driver selection must
	// go through configOverrides (patched post-boot), not env vars.
	const configOverrides = {
		...(d1Name ? { 'database.default': 'cfd1' } : {}),
		...(emailFrom
			? { 'mail.default': 'cloudflare', 'mail.from.address': emailFrom, 'mail.from.name': name }
			: {}),
		...(queueName ? { 'queue.default': 'cloudflare' } : {}),
		...(useBroadcast ? { 'broadcasting.default': 'cloudflare' } : {}),
		...(r2Bucket ? { 'filesystems.default': 'r2' } : {}),
		...(kvNamespace ? { 'cache.default': 'kv' } : {}),
		// Rate limiters need atomic increment — always the DO store's job.
		'cache.limiter': 'do',
	};

	const bindingsSnippet = [
		d1Name ? `\n\tphpBindings: (env) => ({ cfd1: { DB: env.DB } }),` : '',
		Object.keys(configOverrides).length ? `\n\tconfigOverrides: () => (${JSON.stringify(configOverrides)}),` : '',
		emailFrom ? `\n\tonMail: (env, messages) => deliverOutbox(env.EMAIL, messages),` : '',
		queueName
			? `\n\tonQueue: (env, entries) => Promise.all(entries.map((entry) =>\n\t\tenv.QUEUE.send(entry, entry.delaySeconds ? { delaySeconds: entry.delaySeconds } : undefined))),`
			: '',
		useBroadcast ? `\n\tbroadcastBinding: 'BROADCAST_HUB',` : '',
		r2Bucket ? `\n\tr2Binding: 'STORAGE',` : '',
		kvNamespace ? `\n\tkvBinding: 'CACHE',` : '',
		`\n\tcacheHubBinding: 'CACHE_HUB',`,
	].join('');

	const broadcastImport = useBroadcast
		? `\nimport { createBroadcastHubClass } from '@workersphp/runtime/src/BroadcastHub.mjs';`
		: '';
	const broadcastExport = useBroadcast
		? `\nexport const BroadcastHub = createBroadcastHubClass();\n`
		: '';
	const mailImport = emailFrom
		? `\nimport { deliverOutbox } from '@workersphp/runtime/src/mail.mjs';`
		: '';

	// The default binary comes from its own package; alternate variants (the
	// asyncify fallback) live in the runtime's vendor dir, private-monorepo only.
	const binaryBase = wasmVariant === 'php-wasm-85-jspi'
		? '@workersphp/php-wasm-jspi'
		: `@workersphp/runtime/vendor/${wasmVariant}`;

	// One architecture: stateless PHP compute in every colo, state in the
	// primitive with the right concurrency semantics, Durable Objects as
	// coordination components (broadcast hub, cache/lock shards) — never as
	// the app server.
	const workerSource = `// Generated by workersphp. PHP runs in every colo, boots per isolate.
import { createLaravelWorker } from '@workersphp/laravel';
import { createCacheHubClass } from '@workersphp/runtime/src/CacheHub.mjs';${mailImport}${broadcastImport}
import loader from '${binaryBase}/php8.5-web.mjs';
import wasm from '${binaryBase}/php8.5-web.mjs.wasm';

export const CacheHub = createCacheHubClass();
${broadcastExport}
export default createLaravelWorker({
	loader,
	wasm,
	envVars: () => (${envVarsLiteral}),${bindingsSnippet}
});
`;

	const wranglerConfig = {
		...(schemaPath ? { $schema: schemaPath } : {}),
		name,
		main: 'src/index.mjs',
		compatibility_date: '2026-08-01',
		...(accountId ? { account_id: accountId } : {}),
		// The JSPI binary boots + renders in ~1s CPU cold; 30s is ample headroom
		// and makes a genuine hang fail fast instead of burning budget.
		limits: { cpu_ms: 30000 },
		assets: {
			directory: './assets',
			binding: 'ASSETS',
			run_worker_first: true,
		},
		durable_objects: {
			bindings: [
				...(useBroadcast ? [{ name: 'BROADCAST_HUB', class_name: 'BroadcastHub' }] : []),
				{ name: 'CACHE_HUB', class_name: 'CacheHub' },
			],
		},
		// Ordered ledger: broadcast-v1 is already applied on live workers, so
		// cache-v1 must come after it. Append-only — never reorder or rename.
		migrations: [
			...(useBroadcast ? [{ tag: 'broadcast-v1', new_sqlite_classes: ['BroadcastHub'] }] : []),
			{ tag: 'cache-v1', new_sqlite_classes: ['CacheHub'] },
		],
		...(r2Bucket
			? { r2_buckets: [{ binding: 'STORAGE', bucket_name: r2Bucket }] }
			: {}),
		...(kvNamespace
			? { kv_namespaces: [{ binding: 'CACHE', id: kvId }] }
			: {}),
		...(d1Name
			? { d1_databases: [{ binding: 'DB', database_name: d1Name, database_id: d1Id }] }
			: {}),
		...(emailFrom ? { send_email: [{ name: 'EMAIL' }] } : {}),
		...(queueName
			? {
				queues: {
					producers: [{ binding: 'QUEUE', queue: queueName }],
					consumers: [{ queue: queueName, max_batch_size: 10, max_batch_timeout: 0 }],
				},
			}
			: {}),
		...(crons.length ? { triggers: { crons } } : {}),
		...(customDomain
			? { routes: [{ pattern: customDomain, custom_domain: true }, { pattern: `www.${customDomain}`, custom_domain: true }] }
			: {}),
		observability: { enabled: true },
	};

	return { workerSource, wranglerConfig };
}
